name: Release all codemods

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn validate
      - run: yarn test
      - run: yarn community:validate
      - run: yarn worker:sync
      - run: yarn community:release-all
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORKER_PRESHARED_KEY: ${{ secrets.WORKER_PRESHARED_KEY }}
