name: Validate community directory

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn community:validate
      - run: yarn community:release-all-dry
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
